# Generated by Django 4.1.13 on 2023-12-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_file_fileitems_folder_folderitems_delete_customuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderitems',
            name='folder',
        ),
        migrations.DeleteModel(
            name='FileItems',
        ),
        migrations.DeleteModel(
            name='FolderItems',
        ),
    ]
